💥 Promisify and add `mongodb@5` support
reedsy/mongodb-queue pull request #6
Opened 2023-03-01 15:48 UTC by alecgibson

[`mongodb@5`][1] drops support for callbacks, which breaks this library, which is all written with callbacks.

This is a **BREAKING** change which drops callback support from this library as well, and fully embraces promises through `async`/`await` syntax in both the library code and test code.

This allows us to support both `mongodb@4` and `mongodb@5`.

[1]: https://github.com/mongodb/node-mongodb-native/releases/tag/v5.0.0

2023-03-01 16:04 UTC, dawidreedsy requested changes

2023-03-01 16:04 UTC, dawidreedsy commented on mongodb-queue.js
> +    var indexname = await this.col.createIndex({ deleted : 1, visible : 1 })
Any reason we use `var`

2023-03-01 16:04 UTC, dawidreedsy commented on mongodb-queue.js
> +    await this.col.createIndex({deleted: 1}, {sparse: true})
Shouldn't we have just 
```typescript
const [indexname] = await Promise.all([
  this.col.createIndex({ deleted : 1, visible : 1 }),
  this.col.createIndex({ack: 1}, {unique: true, sparse: true})
  this.col.createIndex({deleted: 1}, {sparse: true})
]) 
```

2023-03-01 16:04 UTC, dawidreedsy commented on mongodb-queue.js
> +            // 3) call ourthis to return a new message (if exists)
ourself not ourthis

2023-03-01 16:08 UTC, alecgibson commented on mongodb-queue.js
> +            // 3) call ourthis to return a new message (if exists)
Ha bad find and replace 😅

2023-03-01 16:09 UTC, alecgibson commented on mongodb-queue.js
> +    var indexname = await this.col.createIndex({ deleted : 1, visible : 1 })
Mostly to stay consistent with what was there before, but maybe I can upgrade this too while we're here

2023-03-01 17:18 UTC, dawidreedsy commented on mongodb-queue.js
> +      if (msg.tries > this.maxRetries) {
```suggestion
    if (this.deadQueue && msg.tries > this.maxRetries) {
```

2023-03-02 09:05 UTC, dawidreedsy approved these changes

2023-03-02 09:19 UTC, merged